# Module 3 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module3_derived.rds")

module <- module %>%
  set_variable_labels(aow_recruitment_id = "Age of Wonder recruitment ID",
                      age_survey_y = "Age (years) at survey date",
                      age_survey_m = "Age (months) at survey date",
                      survey_date = "Date survey taken",
                      survey_version = "Survey version",
                      survey_mode = "Survey taken online or offline?",
                      awb5_1_hearing_sght_4 = "Have you ever had your eyes tested outside of school?",
                      awb4_5_location_2 = "Where do you normally eat your meals? Describe",
                      awb2_12_eat_hbt_1_a5 = "Have you deliberately limited food intake to influence weight?",
                      awb2_12_eat_hbt_2_a5 = "Have you gone for long periods of time without eating to influence weight?",
                      awb2_12_eat_hbt_3_a5 = "Has thinking about food/calories made it difficult to concentrate on interests?",
                      awb2_12_eat_hbt_4_a5 = "Has thinking about your weight made it difficult to concentrate on interests?",
                      awb2_12_eat_hbt_5_a5 = "Have you had a definite fear that you might gain weight?",
                      awb2_12_eat_hbt_6_a5 = "Have you had a strong desire to lose weight?",
                      awb2_12_eat_hbt_7_a5 = "Have you tried to control weight by making yourself sick/taking laxatives?",
                      awb2_12_eat_hbt_8_a5 = "Have you exercised compulsively to control weight?",
                      awb2_12_eat_hbt_9_a5 = "Have you felt like you've lost control over eating?",
                      awb2_12_eat_hbt_10_a5 = "How many days do you eat an unusually large amount of food in one go?",
                      awb2_12_wght_1_a5 = "Has your weight influenced how you judge yourself in past 7 days?",
                      awb2_12_wght_2_a5 = "How dissatisfied have you been with your weight in past 7 days?",
                      awb5_1_oral_hlth_2 = "How many times did you clean your teeth yesterday?",
                      awb5_1_oral_hlth_3 = "Do you have a dentist you see every 6 months or so?",
                      awb5_1_oral_hlth_5 = "Why did you last go to the dentist? Describe",
                      awb4_1y_sick = "What prevented you doing normal physical activities last week?",
                      awb4_4_sex_othr = "What is your sex? Describe",
                      awb4_4y_gendersex_f_2 = "Have you started your periods?",
                      awb4_4y_gendersex_y_f_2 = "How old were you when you had your first period?",
                      awb4_3n_bed_2 = "Why didn't you sleep last night? Describe",
                      awb4_4y_ph_otherq = "If you could ask teenagers in Bradford about health, what would it be?",
                      awb5_3_smoke = "How old were you when you first tried smoking a cigarette?",
                      awb5_2_smokevape_prnt = "Do your parents/carers smoke/vape at all?",
                      aw5_2_vape_prnt = "Does anyone smoke/vape indoors at home in rooms you use?",
                      awb5_2y_alcohol_age = "How old were you when you first had an alcoholic drink?",
                      awb5_2y_alcohol_qntty = "Have you ever had 5+ alcoholic drinks at a time?",
                      awb5_2_yalcohol_y_qntty_age = "How old were you when you first had 5+ alcohol drinks in past year?",
                      awb5_2y_alcohol_lctn_1 = "Have you bought alcoholic drinks at any of these places in past week?",
                      awb5_2y_alcohol_lctn_2 = "Which drinks have you had in past week? Describe",
                      awb5_2_gambling_1_a5 = "Have you spent any money on the Lotto?",
                      awb5_2_gambling_2_a5 = "Have you spent any money on shop bought Scratchcards?",
                      awb5_2_gambling_3_a5 = "Have you spent any money on National Lottery instant win games?",
                      awb5_2_gambling_4_a5 = "Have you spent any money on National Lottery games?",
                      awb5_2_gambling_5_a5 = "Have you spent any money on other lotteries?",
                      awb5_2_gambling_6_a5 = "Have you spent any money on fruit/slot machines?",
                      awb5_2_gambling_7_a5 = "Have you spent any money on placing private bet for money?",
                      awb5_2_gambling_8_a5 = "Have you spent any money on playing cards for money?",
                      awb5_2_gambling_9_a5 = "Have you spent any money on bingo at a bingo club?",
                      awb5_2_gambling_10_a5 = "Have you spent any money on bingo at somewhere other than bingo club?",
                      awb5_2_gambling_11_a5 = "Have you visited a betting shop to play machines?",
                      awb5_2_gambling_12_a5 = "Have you personally placed a bet at a betting shop?",
                      awb5_2_gambling_13_a5 = "Have you visited a casino to play casino games?",
                      awb5_2_gambling_14_a5 = "Have you spent any money on gambling websites/apps for real money?",
                      awb5_2y_knife = "Have you carried a knife/other weapon in past year?",
                      awb5_2y_gang_6 = "Have you appeared in court because you were accused of a crime?",
                      awb4_1_sick_a5 = "Were you sick last week, or did anything prevent your normal physical activities?",
                      awb4_1y_sick_a5 = "What prevented you doing normal physical activities in past week?",
                      awb4_3_nap_a5 = "Do you ever take naps during the day?",
                      awb5_2_online_gamb2_a5 = "How do you play online gambling games for real money?",
                      awb5_2_online_gamb3_a5 = "In which ways have you ever used in-game items/currency?",
                      awb5_2_tkn_mny_r8 = "Have you taken money without permission to gamble in past year?",
                      edeqs_total = "Eating Disorder Examination total",
                      edeqs_nas = "Eating Disorder Examination NAs",
                      edeqs_missing = "Eating Disorder Examination missing",
                      edeqs_cat = "Eating Disorder Examination category",
                      paqa_total = "Physical Activity Questionnaire total",
                      paqa_nas = "Physical Activity Questionnaire NAs",
                      paqa_missing = "Physical Activity Questionnaire missing",
                      paqa_mean = "Physical Activity Questionnaire mean",
                      yapsed_total = "Youth Activity Profile total",
                      yapsed_nas = "Youth Activity Profile NAs",
                      yapsed_missing = "Youth Activity Profile missing",
                      yapsed_mean = "Youth Activity Profile mean")


# export
saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module3_labelled.rds")



  