# Module 1 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module1_derived.rds")

# Re-order variables
module <- module %>%
  relocate(awb3_1y_save_mny_a5, .before = awb3_1y_save_mny_a5___1) %>%
  relocate(awb1_2_uknation_idntty_1, .before = awb1_2_uknation_idntty_1___1)%>%
  relocate(awb1_2_ethnicity_arb_r4, .after = ethnicity_2)

# drop some variables we don't want to keep
module <- module |> select(-aw1_2_name_a4,
                           -aw1_2_dob_r4,
                           -awb1_2_dob)
                           
# add value labels
module <- module %>%
  set_value_labels(awb1_2_language_hme___9 = c("Unchecked" = 0,
                                               "Checked: Other (please specify)" = 1))

module <- module %>%
  set_variable_labels(aow_recruitment_id = "Age of Wonder recruitment ID",
                      age_survey_y = "Age (years) at survey date",
                      age_survey_m = "Age (months) at survey date",
                      survey_date = "Date survey taken",
                      survey_version = "Survey version",
                      survey_mode = "Survey taken online or offline?",
                      awb1_2_ethnicity = "What is your ethnicity?",
                      awb1_2_ethnicity_r4 = "What is your ethnicity?",
                      awb1_2_ethnicity_whte_othr = "Any other White background",
                      awb1_2_ethnicity_mix_othr = "Any other mixed/multiple ethnic background",
                      awb1_2_ethnicity_asn_othr = "Any other Asian background",
                      awb1_2_ethnicity_blck_afrcn = "Any other African background",
                      awb1_2_ethnicity_whte_crrbn = "Any other White Caribbean background",
                      awb1_2_ethnicity_othr_othr = "Any other ethnic group",
                      awb1_2_language_hme_othr = "Any other languages spoken at home",
                      awb1_2_religion = "Do you consider yourself to have a religion?",
                      awb1_2y_religion_othr = "Any other religion",
                      awb1_2_sex_othr = "Self describe your sex",
                      awb1_2_gender_othr_r4 = "Self describe your gender",
                      awb1_2_disability = "Do you have any physical/mental health conditions/illnesses?",
                      awb1_2_disability_tme_a4 = "Has your disability lasted/expected to last >=1 year?",
                      awb1_2_disability_impct_a4 = "Do your disabilities reduce your ability to carry out activities?",
                      awb3_1y_save_mny_othr_a5 = "Have your parents discussed cutting back on anything else?",
                      awb3_2_homes_1_ppl_othr = "Who lives in your second home? (choice = other)",
                      awb3_2_homes_1_mthr_1 = "How many of your mothers live in this home?",
                      awb3_2_homes_1_fthr_2 = "How many of your fathers live in this home?",
                      awb3_2_homes_1_grd_3 = "How many of your guardians live in this home?",
                      awb3_2_homes_1_fstcr_4 = "How many of your foster carers live in this home?",
                      awb3_2_homes_1_stpm_5 = "How many of your step mothers live in this home?",
                      awb3_2_homes_1_stpf_6 = "How manay of your step fathers live in this home?",
                      awb3_2_homes_1_mthpt_7 = "How many of your mothers partners live in this home?",
                      awb3_2_homes_1_fthpt_8 = "How many of your fathers partners live in this home?",
                      awb3_2_homes_1_sib_9 = "How many of your siblings live in this home?",
                      awb3_2_homes_1_ant_10 = "How many of your aunties live in this home?",
                      awb3_2_homes_1_unc_11 = "How many of your uncles live in this home?",
                      awb3_2_homes_1_gmthr_12 = "How many of your grandmothers live in this home?",
                      awb3_2_homes_1_gfthr_13 = "How many of your grandfathers live in this home?",
                      awb3_2_homes_1_cus_14 = "How many of your cousins live in this home?",
                      awb3_2_homes_2_ppl_othr = "Who lives in your first home? (choice = other)",
                      awb3_2_homes_2_mthr_1 = "How many of your mothers live in this home?",
                      awb3_2_homes_2_fthr_2 = "How many of your fathers live in this home?",
                      awb3_2_homes_2_grd_3 = "How many of your guardians live in this home?",
                      awb3_2_homes_2_fstcr_4 = "How many of your foster carers live in this home?",
                      awb3_2_homes_2_stpm_5 = "How many of your step mothers live in this home?",
                      awb3_2_homes_2_stpf_6 = "How many of your step fathers live in this home?",
                      awb3_2_homes_2_mthpt_7 = "How many of your mothers partners live in this home?",
                      awb3_2_homes_2_fthpt_8 = "How many of your fathers partners live in this home?",
                      awb3_2_homes_2_ppl_sib_9 = "How many of your siblings live in this home?",
                      awb3_2_homes_2_ant_10 = "How many of your aunties live in this home?",
                      awb3_2_homes_2_ppl_unc_11 = "How many of your uncles live in this home?",
                      awb3_2_homes_2_gmthr_12 = "How many of your grandmothers live in this home?",
                      awb3_2_homes_2_gfthr_13 = "How many of your grandfathers live in this home?",
                      awb3_2_homes_2_cus_14 = "How many of your cousins live in this home?",
                      awb3_3_home_1_jb_othr_1 = "What is their relation to you? (Choice = Other)",
                      awb3_3_home_1_jb_othr_2 = "What is their relation to you? (Choice = Other)",
                      awb3_3_home_1_jb_work_2 = "What is their place of work?",
                      awb3_3_home_1_jb_job_2 = "What job do they do?",
                      awb3_3_home_1_jb_othr_3 = "What is their relation to you? (Choice = Other)",
                      awb3_3_home_1_jb_work_3 = "What is their place of work?",
                      awb3_3_home_1_jb_job_3 = "What job do they do?",
                      awb3_4_prsnl_assts_7_othr = "Do you get money to spend on yourself? (Choice = Other source)",
                      aw3_6_comparison_1 = "If I don't strive to achieve I'll be seen as inferior to others",
                      aw3_6_comparison_2 = "People compare me to others to see if I match up",
                      aw3_6_comparison_3 = "Others will accept me even if I fail",
                      awb3_4_activities_othr = "Do you do any cultural activities you'd like to tell us about?",
                      awb3_4y_motivation = "What motivates you to participate in activities? (Choice = Other)",
                      awb3_4y_restriction = "Why don't you participate in activities that you want to? (Choice = Other)",
                      awb3_4_act_1_who_othr = "Who are you doing this activity with? (choice = other)",
                      awb3_4_act_1_where_othr = "Where do you do this activity? (Choice = other)",
                      awb3_4_act_2_who_othr = "Who are you doing this activity with? (choice = other)",
                      awb3_4_act_2_where_othr = "Where do you do this activity? (Choice = other)",
                      awb3_4_act_3_who_othr = "Who are you doing this activity with? (choice = other)",
                      awb3_4_act_3_where_othr = "Where do you do this activity? (Choice = other)",
                      fas_total = "Family Affluence Scale (FAS) total",
                      fas_nas = "Family Affluence Scale (FAS) NAs",
                      fas_missing = "Family Affluence Scale (FAS) missing",
                      fas_cat = "Family Affluence Scale (FAS) categorical",
                      own_fin_total = "Own Financial Resources total",
                      own_fin_nas = "Own Financial Resources NAs",
                      own_fin_missing = "Own Financial Resources missing",
                      food_avail_total = "Food Availability total",
                      food_avail_nas = "Food Availability NAs",
                      food_avail_missing = "Food Availability missing",
                      sais_total = "Striving to Avoid Inferiority Scale (SAIS) total",
                      sais_nas = "Striving to Avoid Inferiority Scale (SAIS) NAs",
                      sais_missing = "Striving to Avoid Inferiority Scale (SAIS) missing",
                      sais_mean = "Striving to Avoid Inferiority Scale (SAIS) mean",
                      awb1_2_date_emgrtd = "If not born in UK when did you arrive to live here?",
                      awb1_2_uknation_idntty_1 = "How would you describe your national identity?",
                      awb1_2_uknation_idntty_2 = "If other national identity, please describe",
                      awb1_2_language_hme___9 = "Which language is spoken at home? Choice = Other",
                      awb1_2_gender_othr = "Enter the term you use to describe your gender",
                      awb1_3_worries = "Can you tell us 3 things currently worrying you?",
                      awb1_3_happy = "What is currently making you happy?",
                      awb1_4_q_self_a3 = "What question would you ask yourself in 3 years?",
                      awb3_3_home_1_jb_work_1 = "What is Adult 1 place of work?",
                      awb3_3_home_1_jb_job_1 = "What job does Adult 1 do?",
                      awb3_3_home_2_jb_othr_1 = "What other relation is Adult 1 to you?",
                      awb3_3_home_2_jb_work_1 = "What is Adult 1 place of work?",
                      awb3_3_home_2_jb_job_1 = "What job does Adult 1 do?",
                      awb3_3_home_2_jb_othr_2 = "What other relation is Adult 2 to you?",
                      awb3_3_home_2_jb_job_2 = "What job does Adult 2 do?",
                      awb3_3_home_2_jb_othr_3 = "What other relation is Adult 3 to you?",
                      awb3_3_home_2_jb_job_3 = "What job does Adult 3 do?",
                      awb3_7_violence = "Have you been victim of violence in past 1yr?",
                      aw3_7_decisions = "I can influence decisions affecting my local area",
                      awb3_activities_1 = "Did you go to a party in past month?",
                      awb3_activities_2 = "Did you watch live sport in past month?",
                      awb3_activities_3 = "Did you make music/sing in past month?",
                      awb3_activities_4 = "Did you go to a concert/gig in past month?",
                      awb3_activities_5 = "Did you go to other live performance in past month?",
                      awb3_activities_6 = "Did you read for enjoyment in past month?",
                      awb3_activities_7 = "Did you go to youth clubs in past month?",
                      awb3_activities_8 = "Did you go to scouts/guides in past month?",
                      awb3_activities_9 = "Did you go to the library in past month?",
                      awb3_activities_10 = "Did you go to museum/gallery/historic place in past month?",
                      awb3_activities_11 = "Did you do any voluntary work in past month?",
                      awb3_activities_12 = "Did you go to a political meeting in past month?",
                      awb3_activities_13 = "Did you attend a religious service in past month?",
                      awb3_activities_14 = "Did you participate in poetry in past month?",
                      awb3_activities_15 = "Did you do creative writing in past month?",
                      awb3_activities_16 = "Did you take part in performance activities in past month?",
                      awb3_activities_17 = "Did you make any artwork in past month?",
                      awb3_activities_18 = "Did you make any graphic designs in past month?",
                      awb3_4_restriction___1 = "Not enough time to do activities",
                      awb3_4_restriction___2 = "It's too expensive to do activities",
                      awb3_4_restriction___3 = "Health problems prevent me from doing activities",
                      awb3_4_restriction___4 = "No facilities for artistic activities in local area",
                      awb3_4_restriction___5 = "Can't find information about activities on offer",
                      awb3_4_restriction___6 = "The closest facilities for activities are far away",
                      awb3_4_restriction___7 = "I'm not interested in the art activities",
                      awb3_4_restriction___8 = "Other reason for not doing activities",
                      awb3_4_act_1 = "First artistic activity done in past month",
                      awb3_4_act_2 = "Second artistic activity done in past month",
                      awb3_4_act_3 = "Third artistic activity done in past month",
                      awb3_4_talent_in_arts___1 = "Strongly disagree I have great talent in artistic activities",
                      awb3_4_talent_in_arts___2 = "Disagree I have great talent in artistic activities",
                      awb3_4_talent_in_arts___3 = "Neither agree/disagree I have great talent in artistic activities",
                      awb3_4_talent_in_arts___4 = "Strongly disagree I have great talent in artistic activities",
                      awb3_4_talent_in_arts___5 = "Strongly disagree I have great talent in artistic activities",
                      awb3_4_activities_1 = "Did you go to a party in past month?",
                      awb3_4_activities_2 = "Did you watch live sport in past month?",
                      awb3_4_activities_3 = "Did you make music/sing in past month?",
                      awb3_4_activities_4 = "Did you go to a live concert/gig in past month?",
                      awb3_4_activities_5 = "Did you go to a live performance in past month?",
                      awb3_4_activities_6 = "Did you read for enjoyment in past month?",
                      awb3_4_activities_7 = "Did you go to youth clubs in past month?",
                      awb3_4_activities_8 = "Did you go to scouts/guides in past month?",
                      awb3_4_activities_9 = "Did you go to a library in past month?",
                      awb3_4_activities_10 = "Did you go to museum/historic place in past month?",
                      awb3_4_activities_11 = "Did you do voluntary work in past month?",
                      awb3_4_activities_12 = "Did you go to a political meeting in past month?",
                      awb3_4_activities_13 = "Did you attend a religious service in past month?",
                      awb3_4_activities_14 = "Did you participate in poetry in past month?",
                      awb3_4_activities_15 = "Did you do creative writing in past month?",
                      awb3_4_activities_16 = "Did you take part in performance activities in past month?",
                      awb3_4_activities_17 = "Did you do any artwork in past month?",
                      awb3_4_activities_18 = "Did you make any graphic designs in past month?",
                      awb1_2_date_emgrtd_year_a3 = "If you wasnt born in UK when did you arrive to live here?",
                      awb3_1_compare_frnds = "Would you say your family is richer compared to your friends?",
                      awb3_1_warm_engh_a5 = "Are you warm enough at home during winter?",
                      awb3_1_save_mny_a5  = "Parents have talked about cutting back to save money",
                      awb3_3_home_2_jb_work_2 = "What is Adult 2 place of work?",
                      awb3_3_home_2_jb_work_3 = "What is Adult 3 place of work?")


# export
saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module1_labelled.rds")



  