# Module 1 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module1_derived.rds")

module <- module %>%
  set_variable_labels(aow_recruitment_id = "Age of Wonder recruitment ID",
                      age_survey_y = "Age (years) at survey date",
                      age_survey_m = "Age (months) at survey date",
                      survey_date = "Date survey taken",
                      survey_version = "Survey version",
                      survey_mode = "Survey taken online or offline?",
                      awb1_2_ethnicity_whte_othr = "Any other White background",
                      awb1_2_ethnicity_mix_othr = "Any other mixed/multiple ethnic background",
                      awb1_2_ethnicity_asn_othr = "Any other Asian background",
                      awb1_2_ethnicity_blck_afrcn = "Any other African background",
                      awb1_2_ethnicity_whte_crrbn = "Any other White Caribbean background",
                      awb1_2_ethnicity_othr_othr = "Any other ethnic group",
                      awb1_2_language_hme_othr = "Any other languages spoken at home",
                      awb1_2_religion = "Do you consider yourself to have a religion?",
                      awb1_2y_religion_othr = "Any other religion",
                      awb1_2_sex_othr = "Self describe your sex",
                      awb1_2_gender_othr_r4 = "Self describe your gender",
                      awb1_2_disability = "Do you have any physical/mental health conditions/illnesses?",
                      awb1_2_disability_tme_a4 = "Has your disability lasted/expected to last >=1 year?",
                      awb1_2_disability_impct_a4 = "Do your disabilities reduce your ability to carry out activities?",
                      awb3_1y_save_mny_othr_a5 = "Have your parents discussed cutting back on anything else?",
                      awb3_2_homes_1_ppl_othr = "Who lives in your second home? (choice = other)",
                      awb3_2_homes_1_mthr_1 = "How many of your mothers live in this home?",
                      awb3_2_homes_1_fthr_2 = "How many of your fathers live in this home?",
                      awb3_2_homes_1_grd_3 = "How many of your guardians live in this home?",
                      awb3_2_homes_1_fstcr_4 = "How many of your foster carers live in this home?",
                      awb3_2_homes_1_stpm_5 = "How many of your step mothers live in this home?",
                      awb3_2_homes_1_stpf_6 = "How manay of your step fathers live in this home?",
                      awb3_2_homes_1_mthpt_7 = "How many of your mothers partners live in this home?",
                      awb3_2_homes_1_fthpt_8 = "How many of your fathers partners live in this home?",
                      awb3_2_homes_1_sib_9 = "How many of your siblings live in this home?",
                      awb3_2_homes_1_ant_10 = "How many of your aunties live in this home?",
                      awb3_2_homes_1_unc_11 = "How many of your uncles live in this home?",
                      awb3_2_homes_1_gmthr_12 = "How many of your grandmothers live in this home?",
                      awb3_2_homes_1_gfthr_13 = "How many of your grandfathers live in this home?",
                      awb3_2_homes_1_cus_14 = "How many of your cousins live in this home?",
                      awb3_2_homes_2_ppl_othr = "Who lives in your first home? (choice = other)",
                      awb3_2_homes_2_mthr_1 = "How many of your mothers live in this home?",
                      awb3_2_homes_2_fthr_2 = "How many of your fathers live in this home?",
                      awb3_2_homes_2_grd_3 = "How many of your guardians live in this home?",
                      awb3_2_homes_2_fstcr_4 = "How many of your foster carers live in this home?",
                      awb3_2_homes_2_stpm_5 = "How many of your step mothers live in this home?",
                      awb3_2_homes_2_stpf_6 = "How manay of your step fathers live in this home?",
                      awb3_2_homes_2_mthpt_7 = "How many of your mothers partners live in this home?",
                      awb3_2_homes_2_fthpt_8 = "How many of your fathers partners live in this home?",
                      awb3_2_homes_2_ppl_sib_9 = "How many of your siblings live in this home?",
                      awb3_2_homes_2_ant_10 = "How many of your aunties live in this home?",
                      awb3_2_homes_2_ppl_unc_11 = "How many of your uncles live in this home?",
                      awb3_2_homes_2_gmthr_12 = "How many of your grandmothers live in this home?",
                      awb3_2_homes_2_gfthr_13 = "How many of your grandfathers live in this home?",
                      awb3_2_homes_2_cus_14 = "How many of your cousins live in this home?",
                      awb3_3_home_1_jb_othr_1 = "What is their relation to you? (Choice = Other)",
                      awb3_3_home_1_jb_othr_2 = "What is their relation to you? (Choice = Other)",
                      awb3_3_home_1_jb_work_2 = "What is their place of work?",
                      awb3_3_home_1_jb_job_2 = "What job do they do?",
                      awb3_3_home_1_jb_othr_3 = "What is their relation to you? (Choice = Other)",
                      awb3_3_home_1_jb_work_3 = "What is their place of work?",
                      awb3_3_home_1_jb_job_3 = "What job do they do?",
                      awb3_4_prsnl_assts_7_othr = "Do you get money to spend on yourself? (Choice = Other source)",
                      aw3_6_comparison_1 = "If I don't strive to achieve I'll be seen as inferior to others",
                      aw3_6_comparison_2 = "People compare me to others to see if I match up",
                      aw3_6_comparison_3 = "Others will accept me even if I fail",
                      awb3_4_activities_othr = "Do you do any cultural activities you'd like to tell us about?",
                      awb3_4y_motivation = "What motivates you to participate in activities? (Choice = Other)",
                      awb3_4y_restriction = "Why don't you participate in activities that you want to? (Choice = Other)",
                      awb3_4_act_1_who_othr = "Who are you doing this activity with? (choice = other)",
                      awb3_4_act_1_where_othr = "Where do you do this activity? (Choice = other)",
                      awb3_4_act_2_who_othr = "Who are you doing this activity with? (choice = other)",
                      awb3_4_act_2_where_othr = "Where do you do this activity? (Choice = other)",
                      awb3_4_act_3_who_othr = "Who are you doing this activity with? (choice = other)",
                      awb3_4_act_3_where_othr = "Where do you do this activity? (Choice = other)",
                      fas_total = "Family Affluence Scale (FAS) total",
                      fas_nas = "Family Affluence Scale (FAS) NAs",
                      fas_missing = "Family Affluence Scale (FAS) missing",
                      fas_cat = "Family Affluence Scale (FAS) categorical",
                      own_fin_total = "Own Financial Resources total",
                      own_fin_nas = "Own Financial Resources NAs",
                      own_fin_missing = "Own Financial Resources missing",
                      food_avail_total = "Food Availability total",
                      food_avail_nas = "Food Availability NAs",
                      food_avail_missing = "Food Availability missing",
                      sais_total = "Striving to Avoid Inferiority Scale (SAIS) total",
                      sais_nas = "Striving to Avoid Inferiority Scale (SAIS) NAs",
                      sais_missing = "Striving to Avoid Inferiority Scale (SAIS) missing",
                      sais_mean = "Striving to Avoid Inferiority Scale (SAIS) mean")


# Re-order variables


# export
saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module1_labelled.rds")



  