# Module 232 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module232_integrated.rds")

# these are empty and seem to have been recoded in an ealier release
module <- module |> select(-awb6_1_social_media_r10,
                           -awb6_1_negative_exp_r5)

# 80 chars:                           
################################################################################

module <- module %>%
  set_variable_labels(awb2_1_illhealth_1 = "How often do you feel sad or empty?",
                      awb2_1_illhealth_2 = "How often do you worry when you think you have done poorly at something?",
                      awb2_1_illhealth_3 = "How often do you feel afraid to be home alone?",
                      awb2_1_illhealth_4 = "How often do you feel nothing is much fun anymore?",
                      awb2_1_illhealth_5 = "How often do you worry that something awful will happen to someone in family?",
                      awb2_1_illhealth_6 = "How often do you feel afraid of being in crowded places?",
                      awb2_1_illhealth_7 = "How often do you worry what others think of you?",
                      awb2_1_illhealth_8 = "How often do you have trouble sleeping?",
                      awb2_1_illhealth_9 = "How often do you feel scared to sleep alone?",
                      awb2_1_illhealth_10 = "How often do you have problems with appetite?",
                      awb2_1_illhealth_11 = "How often do you suddenly become dizzy/faint for no reason?",
                      awb2_1_illhealth_12 = "How often do you have to do some things over and over again?",
                      awb2_1_illhealth_13 = "How often do you have no energy for things?",
                      awb2_1_illhealth_14 = "How often do you suddenly tremble/shake for no reason?",
                      awb2_1_illhealth_15 = "How often is it when you can't think clearly?",
                      awb2_1_illhealth_16 = "How often do you feel worthless?",
                      awb2_1_illhealth_17 = "How often do you think special thoughts to stop bad happening?",
                      awb2_1_illhealth_18 = "How often do you think about death?",
                      awb2_1_illhealth_19 = "How often do you feel like you don't want to move?",
                      awb2_1_illhealth_20 = "How often do you worry about being scared for no reason?",
                      awb2_1_illhealth_21 = "How often do you feel you are tired alot?",
                      awb2_1_illhealth_22 = "How often do you feel afraid you will make a fool of yourself?",
                      awb2_1_illhealth_23 = "How often do you do something the right way to stop bad things happening?",
                      awb2_1_illhealth_24 = "How often do you feel restless?",
                      awb2_1_illhealth_25 = "How often do you worry something bad will happen to you?",
                      awb2_1_sdq_1_a10 = "SDQ: last 6mo: I try to be nice to other people. I care about their feelings",
                      awb2_1_sdq_2_a10 = "SDQ: last 6mo: I am restless, I cannot stay still for long",
                      awb2_1_sdq_3_a10 = "SDQ: last 6mo: I get a lot of headaches, stomach-aches, or sickness",
                      awb2_1_sdq_4_a10 = "SDQ: last 6mo: I usually share with others (food, games, pens etc.)",
                      awb2_1_sdq_5_a10 = "SDQ: last 6mo: I get very angry and often lose my temper",
                      awb2_1_sdq_6_a10 = "SDQ: last 6mo: I am usually on my own. I generally play alone or keep to myself",
                      awb2_1_sdq_7_a10 = "SDQ: last 6mo: I usually do as I am told",
                      awb2_1_sdq_8_a10 = "SDQ: last 6mo: I worry a lot",
                      awb2_1_sdq_9_a10 = "SDQ: last 6mo: I am helpful if someone is hurt, upset, or feeling ill",
                      awb2_1_sdq_10_a10 = "SDQ: last 6mo: I am constantly fidgeting or squirming",
                      awb2_1_sdq_11_a10 = "SDQ: last 6mo: I have one good friend or more",
                      awb2_1_sdq_12_a10 = "SDQ: last 6mo: I fight a lot.  I can make other people do what I want",
                      awb2_1_sdq_13_a10 = "SDQ: last 6mo: I am often unhappy, down-hearted, or tearful",
                      awb2_1_sdq_14_a10 = "SDQ: last 6mo: Other people my age generally like me",
                      awb2_1_sdq_15_a10 = "SDQ: last 6mo: I am easily distracted, I find it difficult to concentrate",
                      awb2_1_sdq_16_a10 = "SDQ: last 6mo: I am nervous in new situations. I easily lose confidence",
                      awb2_1_sdq_17_a10 = "SDQ: last 6mo: I am kind to younger children",
                      awb2_1_sdq_18_a10 = "SDQ: last 6mo: I am often accused of lying or cheating",
                      awb2_1_sdq_19_a10 = "SDQ: last 6mo: Other children or young people pick on me or bully me",
                      awb2_1_sdq_20_a10 = "SDQ: last 6mo: I often volunteer to help others (parents, teachers, children)",
                      awb2_1_sdq_21_a10 = "SDQ: last 6mo: I think before I do things",
                      awb2_1_sdq_22_a10 = "SDQ: last 6mo: I take things that are not mine from home, school or elsewhere",
                      awb2_1_sdq_23_a10 = "SDQ: last 6mo: I get on better with adults than with people my own age",
                      awb2_1_sdq_24_a10 = "SDQ: last 6mo: I have many fears, I am easily scared",
                      awb2_1_sdq_25_a10 = "SDQ: last 6mo: I finish the work I'm doing. My attention is good",
                      awb2_2_optmstc_1_a4 = "Have you felt optimistic about the future over past 2 weeks?",
                      awb2_2_useful_2_a4 = "Have you felt useful over past 2 weeks?",
                      awb2_2_relxed_3_a4 = "Have you felt relaxed over the past 2 weeks?",
                      awb2_2_problems_4_a4 = "Have you dealt with problems well over the past 2 weeks?",
                      awb2_2_think_clr_5_a4 = "Have you been thinking clearly over the past 2 weeks?",
                      awb2_2_close_othrs_6_a4 = "Have you felt close to others over the past 2 weeks?",
                      awb2_2_own_mnd_7_a4 = "Have you made your own mind up about things over past 2 weeks?",
                      awb2_3_self_effccy = "When you find something hard can you work out what to do?",
                      awb2_4_loneliness_1 = "How often do you feel that you lack friendship?",
                      awb2_4_loneliness_2 = "How often do you feel left out?",
                      awb2_4_loneliness_3 = "How often do you feel isolated from others?",
                      awb2_4_loneliness_4 = "How often do you feel alone?",
                      awb2_9_trust = "Would you say most people can be trusted/you can't be too careful?",
                      awb2_9_seek_hlp_ppl_1_r4 = "How likely would you seek help from partner?",
                      awb2_9_seek_hlp_ppl_2 = "How likely would you seek help from a friend?",
                      awb2_9_seek_hlp_ppl_3 = "How likely would you seek help from a parent/carer?",
                      awb2_9_seek_hlp_ppl_4 = "How likely would you seek help from another relative/family member?",
                      awb2_9_seek_hlp_ppl_5 = "How likely would you seek help from a mental health professional?",
                      awb2_9_seek_hlp_ppl_6 = "How likely would you seek help from a phone helpline?",
                      awb2_9_seek_hlp_ppl_7 = "How likely would you seek help from a doctor/GP?",
                      awb2_9_seek_hlp_ppl_8 = "How likely would you seek help from a religious leader?",
                      awb2_9_seek_hlp_ppl_10 = "How likely is it you would not seek help from anyone?",
                      awb2_9_seek_hlp_ppl_9_a_4 = "How likely would you seek help from a teacher/other school staff?",
                      awb2_9_seek_hlp_ppl_othr_a3 = "Would you seek help from another not listed above?",
                      awb2_9_seek_hlp_ppl_11 = "Would you seek help from another not listed above? (list)",
                      awb2_9_seek_hurt_self_a5 = "In the past year, have you hurt yourself on purpose in any way?",
                      awb2_9_resil1_a5 = "I tend to bounce back quickly after hard times",
                      awb2_9_resil2_a5 = "I have a hard time making it through stressful events",
                      awb2_9_resil3_a5 = "It does not take me long to recover from a stressful event",
                      awb2_9_resil4_a5 = "It is hard for me to snap back when something bad happens",
                      awb2_9_resil5_a5 = "I usually come through difficult times with little trouble",
                      awb2_9_resil6_a5 = "I tend to take a long time to get over set-backs in my life",
                      awb2_11_psychosis_3_r4 = "Have you ever heard voices that others cannot hear?",
                      awb2_11_upsetting_3_a4 = "How upsetting if you heard voices others couldn't hear?",
                      awb2_11_pst_yr_3_a4 = "How often have you heard voices that other people couldnt hear in the last year?",
                      awb2_11_psychosis_5_r4 = "Have you ever seen something others cannot see?",
                      awb2_11_upsetting_5_a4 = "How upsetting if you have seen something other couldn't see?",
                      awb2_11_pst_yr_5_a4 = "How often have you seen something others couldn't see in past year?",
                      awb2_11_psychosis_2_r4 = "Have you ever thought you was being followed/spied on?",
                      awb2_11_upsetting_2_a4 = "How upsetting if you thought you were being followed/spied on?",
                      awb2_11_pst_yr_2_a4 = "How often have you thought you were being followed or spied on in the past year?",
                      awb2_11_plot_hrm_a4 = "Ever believed people following you/spying on you as part of a plot",
                      awb2_11_psychosis_10_r4 = "Have other people ever read your thoughts?",
                      awb2_11_upsetting_10_a4 = "At its worst, how upsetting did you find people reading your thoughts?",
                      awb2_11_pst_yr_10_a4 = "How often have you believed that other people can read your thoughts in the past",
                      awb2_11_pwrs_read_a4 = "Do you think people use special powers to read your thoughts?",
                      awb2_11_psychosis_1_r4 = "Have you thought you were being sent messages through TV arranged just for you?",
                      awb2_11_upsetting_1_a4 = "How upsetting if you believed you were being sent special messages through TV",
                      awb2_11_pst_yr_1_a4 = "How often have you been sent special messages through TV in the past year?",
                      awb2_11_psychosis_4_r4 = "Have you ever felt under control of a special power?",
                      awb2_11_upsetting_4_a4 = "How upsetting if you felt under control of a special power?",
                      awb2_11_pst_yr_4_a4 = "How often you thought you were under control of a special power in past year",
                      awb2_11_cntrl_who_a4 = "Who did you think was controlling you (at any time in the past)?",
                      awb2_11_cntrl_no_will_a4 = "Did it control what you were doing or thinking, no will of your own",
                      awb2_11_psychosis_9_r4 = "Have you ever felt like you have special powers?",
                      awb2_11_pst_yr_9_a4 = "How often thought you were very special/have special powers past year",
                      awb7_1_wntr_mnths = "How often do you visit parks and green spaces? During the winter months",
                      awb7_1_smmr_mnths = "How often do you visit parks and green spaces? During the spring/summer months",
                      awb7_2_pollution = "What do you think about the air quality in Bradford?",
                      awb7_3_clmte_chnge_feelng = "How pos/neg do you feel about the future of the environment?",
                      awb7_1_like = "School: I enjoy school",
                      awb7_1_trust = "School: There is an adult at school I can talk to if something is worrying me",
                      awb7_1_bullying_1 = "Is bullying a problem at your school?",
                      awb7_1_safe_r8 = "I feel safe when I am at school",
                      awb7_2_grades_a5 = "School pressure: Competition with other people for grades is intense",
                      awb7_2_fam_diss_a5 = "School pressure: If I dont do well in school my family will be disappointed",
                      awb7_2_prnt_preshr_a5 = "School pressure: My teachers put too much pressure on me to do well in school",
                      awb7_2_progrssng_a5 = "School pressure: Im worried about progressing in the future",
                      awb7_2_dnt_do_well_a5 = "School pressure: If I dont do well in school, Ill be a failure",
                      awb7_2_acad_strss_r8 = "School pressure: Often feel stressed because of pressure to do well in school",
                      awb7_2_test_wrries_a5 = "School pressure: I worry about doing well in tests, exams and assessments",
                      awb2_7_friends_physcl_r10 = "How many in-person friends do you have?",
                      awb2_7_friends_onln_r10 = "How many online friends do you have?",
                      awb2_7_friends_clse_a5 = "Do you have any close friends?",
                      awb8_1_morality_1_r10 = "Do people your age: Start a fight with someone?",
                      awb8_1_morality_2_r10 = "Do people your age: Write things/spray paint on a building, fence, train",
                      awb8_1_morality_3_r10 = "Do people your age: Take something from a shop without paying for it",
                      awb8_1_morality_4_r10 = "Do people your age: Copy/download music/games/films without paying",
                      awb8_3_bully = "How often have you taken part in bullying somebody at school?",
                      awb8_2_bullied = "How often have you been bullied at school in the past couple of months?",
                      awb8_2_bully_onlne = "In the past couple of months, how often have you taken part in online bullying?",
                      awb8_2_bullied_onlne = "How often have you been bullied online?",
                      awb8_2_club_1 = "Have you ever been discouraged from joining a club/group?",
                      awb8_2_club_rsn_1___1 = "Were you discourage from joining a club/group because your ethnicity?",
                      awb8_2_club_rsn_1___2 = "Were you discourage from joining a club/group because your sex/gender?",
                      awb8_2_club_rsn_1___3 = "Were you discourage from joining a club/group because your disability?",
                      awb8_2_club_rsn_1___4 = "Were you discourage from joining a club/group because your religion?",
                      awb8_2_club_rsn_1___5 = "Were you discourage from joining a club/group because your class?",
                      awb8_2_club_rsn_1___6 = "Were you discourage from joining a club/group because your neurodiversity?",
                      awb8_2_club_rsn_1___7 = "Were you discourage from joining a club/group because your sexuality?",
                      awb8_2_club_rsn_1___8 = "Were you discourage from joining a club/group because of something else?",
                      awb8_2_club_rsn_2 = "Were you discourage from joining a club/group because of something else?",
                      awb8_2_excl_2 = "Have others your age not included you in their activities?",
                      awb8_2_excl_rsn_1___1 = "Were you excluded from activities because of your ethnicity?",
                      awb8_2_excl_rsn_1___2 = "Were you excluded from activities because of your sex/gender?",
                      awb8_2_excl_rsn_1___3 = "Were you excluded from activities because of your disability?",
                      awb8_2_excl_rsn_1___4 = "Were you excluded from activities because of your religion?",
                      awb8_2_excl_rsn_1___5 = "Were you excluded from activities because of your class?",
                      awb8_2_excl_rsn_1___6 = "Were you excluded from activities because of your neurodiversity?",
                      awb8_2_excl_rsn_1___7 = "Were you excluded from activities because of your sexuality?",
                      awb8_2_excl_rsn_1___8 = "Were you excluded from activities because of something else?",
                      awb8_2_excl_rsn_2 = "Were you excluded from activities because of something else?",
                      awb8_2_age_3 = "Have people expected less of you than others your age?",
                      awb8_2_age_rsn_1___1 = "Did people expect less of you because of your ethnicity?",
                      awb8_2_age_rsn_1___2 = "Did people expect less of you because of your sex/gender?",
                      awb8_2_age_rsn_1___3 = "Did people expect less of you because of your disability?",
                      awb8_2_age_rsn_1___4 = "Did people expect less of you because of your religion?",
                      awb8_2_age_rsn_1___5 = "Did people expect less of you because of your class?",
                      awb8_2_age_rsn_1___6 = "Did people expect less of you because of your neurodiversity?",
                      awb8_2_age_rsn_1___7 = "Did people expect less of you because of your sexuality?",
                      awb8_2_age_rsn_1___8 = "Did people expect less of you because of something else?",
                      awb8_2_age_rsn_2 = "Did people expect less of you because of something else?",
                      awb8_2_lang_4 = "Have people assumed your English was poor?",
                      awb8_2_lang_rsn_1___1 = "Did people assume your English was poor because of your ethnicity?",
                      awb8_2_lang_rsn_1___2 = "Did people assume your English was poor because of your sex/gender?",
                      awb8_2_lang_rsn_1___3 = "Did people assume your English was poor because of your disability?",
                      awb8_2_lang_rsn_1___4 = "Did people assume your English was poor because of your religion?",
                      awb8_2_lang_rsn_1___5 = "Did people assume your English was poor because of your class?",
                      awb8_2_lang_rsn_1___6 = "Did people assume your English was poor because of your neurodiversity?",
                      awb8_2_lang_rsn_1___7 = "Did people assume your English was poor because of your sexuality?",
                      awb8_2_lang_rsn_1___8 = "Did people assume your English was poor because of something else?",
                      awb8_2_lang_rsn_2 = "Did people assume your English was poor because of something else?",
                      awb8_2_police_5 = "Have you ever been hassled by police?",
                      awb8_2_police_rsn_1___1 = "Were you hassled by police because of your ethnicity?",
                      awb8_2_police_rsn_1___2 = "Were you hassled by police because of your sex/gender?",
                      awb8_2_police_rsn_1___3 = "Were you hassled by police because of your disability?",
                      awb8_2_police_rsn_1___4 = "Were you hassled by police because of your religion?",
                      awb8_2_police_rsn_1___5 = "Were you hassled by police because of your class?",
                      awb8_2_police_rsn_1___6 = "Were you hassled by police because of your neurodiversity?",
                      awb8_2_police_rsn_1___7 = "Were you hassled by police because of your sexuality?",
                      awb8_2_police_rsn_1___8 = "Were you hassled by police because of something else?",
                      awb8_2_police_rsn_2 = "Were you hassled by police because of something else?",
                      awb8_2_shop_6 = "Have you ever been hassled by staff in a shop?",
                      awb8_2_shop_rsn_1___1 = "Were you hassled by staff in a shop because of your ethnicity?",
                      awb8_2_shop_rsn_1___2 = "Were you hassled by staff in a shop because of your sex/gender?",
                      awb8_2_shop_rsn_1___3 = "Were you hassled by staff in a shop because of your disability?",
                      awb8_2_shop_rsn_1___4 = "Were you hassled by staff in a shop because of your religion?",
                      awb8_2_shop_rsn_1___5 = "Were you hassled by staff in a shop because of your class?",
                      awb8_2_shop_rsn_1___6 = "Were you hassled by staff in a shop because of your neurodiversity?",
                      awb8_2_shop_rsn_1___7 = "Were you hassled by staff in a shop because of your sexuality?",
                      awb8_2_shop_rsn_1___8 = "Were you hassled by staff in a shop because of something else?",
                      awb8_2_shop_rsn_2 = "Were you hassled by staff in a shop because of something else?",
                      awb8_2_names_7 = "Have you ever been called insulting names?",
                      awb8_2_names_rsn_1___1 = "Were you called insulting names because of your ethnicity?",
                      awb8_2_names_rsn_1___2 = "Were you called insulting names because of your sex/gender?",
                      awb8_2_names_rsn_1___3 = "Were you called insulting names because of your disability?",
                      awb8_2_names_rsn_1___4 = "Were you called insulting names because of your religion?",
                      awb8_2_names_rsn_1___5 = "Were you called insulting names because of your class?",
                      awb8_2_names_rsn_1___6 = "Were you called insulting names because of your neurodiversity?",
                      awb8_2_names_rsn_1___7 = "Were you called insulting names because of your sexuality?",
                      awb8_2_names_rsn_1___8 = "Were you called insulting names because of something else?",
                      awb8_2_names_rsn_2 = "Were you called insulting names because of something else?",
                      awb8_2_service_8 = "Have you ever received poor service in a shop/restaurant?",
                      awb8_2_service_rsn_1___1 = "Did you receive poor service because of your ethnicity?",
                      awb8_2_service_rsn_1___2 = "Did you receive poor service because of your sex/gender?",
                      awb8_2_service_rsn_1___3 = "Did you receive poor service because of your disability?",
                      awb8_2_service_rsn_1___4 = "Did you receive poor service because of your religion?",
                      awb8_2_service_rsn_1___5 = "Did you receive poor service because of your class?",
                      awb8_2_service_rsn_1___6 = "Did you receive poor service because of your neurodiversity?",
                      awb8_2_service_rsn_1___7 = "Did you receive poor service because of your sexuality?",
                      awb8_2_service_rsn_1___8 = "Did you receive poor service because of something else?",
                      awb8_2_service_rsn_2 = "Did you receive poor service because of something else?",
                      awb8_2_int_9 = "Have people ever acted as though you were not intelligent?",
                      awb8_2_int_rsn_1___1 = "Did people act as though you weren't intelligent because of your ethnicity?",
                      awb8_2_int_rsn_1___2 = "Did people act as though you weren't intelligent because of your sex/gender?",
                      awb8_2_int_rsn_1___3 = "Did people act as though you weren't intelligent because of your disability?",
                      awb8_2_int_rsn_1___4 = "Did people act as though you weren't intelligent because of your religion?",
                      awb8_2_int_rsn_1___5 = "Did people act as though you weren't intelligent because of your class?",
                      awb8_2_int_rsn_1___6 = "Did people act as though you weren't intelligent because of your neurodiversity?",
                      awb8_2_int_rsn_1___7 = "Did people act as though you werent intelligent because of your sexuality?",
                      awb8_2_int_rsn_1___8 = "Did people act as though you weren't intelligent because of something else?",
                      awb8_2_int_rsn_2 = "Did people act as though you weren't intelligent because of something else?",
                      awb8_2_afraid_10 = "Have people ever acted like they're afraid of you?",
                      awb8_2_afraid_rsn_1___1 = "Did people act afraid of you because of your ethnicity?",
                      awb8_2_afraid_rsn_1___2 = "Did people act afraid of you because of your sex/gender?",
                      awb8_2_afraid_rsn_1___3 = "Did people act afraid of you because of your disability?",
                      awb8_2_afraid_rsn_1___4 = "Did people act afraid of you because of your religion?",
                      awb8_2_afraid_rsn_1___5 = "Did people act afraid of you because of your class?",
                      awb8_2_afraid_rsn_1___6 = "Did people act afraid of you because of your neurodiversity?",
                      awb8_2_afraid_rsn_1___7 = "Did people act afraid of you because of your sexuality?",
                      awb8_2_afraid_rsn_1___8 = "Did people act afraid of you because of something else?",
                      awb8_2_afraid_rsn_2 = "Did people act afraid of you because of something else?",
                      awb8_2_threat_11 = "Have you ever been threatened?",
                      awb8_2_threat_rsn_1___1 = "Were you threatened because of your ethnicity?",
                      awb8_2_threat_rsn_1___2 = "Were you threatened because of your sex/gender?",
                      awb8_2_threat_rsn_1___3 = "Were you threatened because of your disability?",
                      awb8_2_threat_rsn_1___4 = "Were you threatened because of your religion?",
                      awb8_2_threat_rsn_1___5 = "Were you threatened because of your class?",
                      awb8_2_threat_rsn_1___6 = "Were you threatened because of your neurodiversity?",
                      awb8_2_threat_rsn_1___7 = "Were you threatened because of your sexuality?",
                      awb8_2_threat_rsn_1___8 = "Were you threatened because of something else?",
                      awb8_2_threat_rsn_2 = "Were you threatened because of something else?",
                      awb6_1_social_media_r10___1 = "Which social media platforms do you use? Tick all that apply (choice=Facebook)",
                      awb6_1_social_media_r10___2 = "Which social media platforms do you use? Tick all that apply (choice=Instagram)",
                      awb6_1_social_media_r10___3 = "Which social media platforms do you use? Tick all that apply (choice=X (formerly",
                      awb6_1_social_media_r10___4 = "Which social media platforms do you use? Tick all that apply (choice=TikTok)",
                      awb6_1_social_media_r10___5 = "Which social media platforms do you use? Tick all that apply (choice=Snapchat)",
                      awb6_1_social_media_r10___11 = "Which social media platforms do you use? Tick all that apply (choice=Other)",
                      awb6_1_social_media_othr = "Which social media platforms do you use? Tick all that apply (choice=Other)",
                      awb6_1_time_weekday = "How many hours spent using social media during term time?",
                      awb6_1_time_weekend = "How many hrs do you spend using social media at weekend in term time?",
                      awb6_1_positive_exp___1 = "Has connecting with friends been a positive experience of social media?",
                      awb6_1_positive_exp___2 = "Has viewing enjoyable content been a positive experience of social media?",
                      awb6_1_positive_exp___3 = "Has learning new things  been a positive experience of social media?",
                      awb6_1_positive_exp___4 = "Has accessing support been a positive experience of social media?",
                      awb6_1_positive_exp___5 = "Has engaging positively with issues been a positive experience of social media?",
                      awb6_1_positive_exp___6 = "Has there been any other positive experience of social media?",
                      awb6_1_positive_exp_othr = "Has there been any other positive experience of social media?",
                      awb6_1_negative_exp_r5___1 = "Has people being unpleasant about you been negative experience of social media?",
                      awb6_1_negative_exp_r5___2 = "Has people bullying you been a negative experience of social media?",
                      awb6_1_negative_exp_r5___3 = "Has upsetting content been a negative experience of social media?",
                      awb6_1_negative_exp_r5___4 = "Has sexually explicit images been a negative experience of social media?",
                      awb6_1_negative_exp_r5___5 = "Has regrettably posting something online been a negative experience of social media?",
                      awb6_1_negative_exp_r5___6 = "You havent experience any negative experience of social media",
                      awb6_1_negative_exp_r5___7 = "You've had a negative experience of social media for another reason",
                      awb6_1_neg_exp_othr_r5 = "You've had a negative experience of social media for another reason",
                      awb6_1_pos_neg = "Has your experience of using social media been mostly positive or negative?",
                      awb6_6_int_hme = "Do you have access to the internet at home?",
                      awb6_6_int_hme_gd = "How good is your internet at home?"
  )


# export
saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module232_labelled.rds")



  