# Module 2 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module2_derived.rds")


module <- module %>%
  set_variable_labels(aow_recruitment_id = "Age of Wonder recruitment ID",
                      year_group = "School year group",
                      age_survey_m = "Age (months) at survey date",
                      age_survey_y = "Age (years) at survey date",
                      survey_date = "Date survey taken",
                      survey_version = "Survey version",
                      survey_mode = "Survey taken online or offline?",
                      awb2_9_seek_hlp_ppl_1_r4 = "How likely would you seek help from partner?",
                      awb2_9_seek_hlp_ppl_11 = "Would you seek help from someone not listed? List in space provided",
                      awb2_11_psychosis_3_r4 = "Have you ever heard voices that others cannot hear?",
                      awb2_11_psychosis_5_r4 = "Have you ever seen something others cannot see?",
                      awb2_11_psychosis_2_r4 = "Have you ever thought you was being followed/spied on?",
                      awb2_11_psychosis_10_r4 = "Have other people ever read your thoughts?",
                      awb2_11_pwrs_read_a4 = "Do you think people use special powers to read your thoughts?",
                      awb2_11_psychosis_1_r4 = "Have you thought you were being sent messages through TV arranged just for you?",
                      awb2_11_psychosis_4_r4 = "Have you ever felt under control of a special power?",
                      awb2_11_psychosis_9_r4 = "Have you ever felt like you have special powers?",
                      awb7_3_worry_specify = "Are you not worried about impact of climate change? Please specify",
                      awb7_3_chngs_plse_specify = "What changes have you made to tackle climate change? Specify",
                      awb7_3_no_chnges_specify = "What reason have you not made changes to tackle climate change? Specify",
                      feedback_mental_hlth = "Feedback for mental health questions",
                      rcad_ga = "Revised childrens anxiety and depression scale. General anxiety",
                      rcad_md = "Revised childrens anxiety and depression scale. Major depression",
                      rcad_total = "Revised childrens anxiety and depression scale. Total",
                      rcad_nas = "Revised childrens anxiety and depression scale. NAs",
                      rcad_ga_miss = "Revised childrens anxiety and depression scale. General anxiety NAs",
                      rcad_md_miss = "Revised childrens anxiety and depression scale. Major depression NAs",
                      rcad_missing = "Revised childrens anxiety and depression scale. Total NAs",
                      depression_int = "Depression int",
                      depression_factor = "Depression factor",
                      anxiety_int = "Anxiety int",
                      anxiety_factor = "Anxiety factor",
                      total_int = "Total int",
                      total_factor = "Total factor",
                      rcad_md_t = "RCADS Depression (higher = more depressed)",
                      rcad_ga_t = "RCADS Anxiety (higher = more anxiety)",
                      rcad_total_t = "Revised childrens anxiety and depression scale (RCADS) Total sum",
                      rcad_md_cat = "Revised childrens anxiety and depression scale. Major depression category",
                      rcad_ga_cat = "Revised childrens anxiety and depression scale. General anxiety category",
                      rcad_total_cat = "Revised childrens anxiety and depression scale. Total category",
                      wellbeing = "Warwick-Edinburgh Mental Wellbeing Scale (higher = greater wellbeing)",
                      wellbeing_nas = "Warwick-Edinburgh Mental Wellbeing Scale NAs",
                      wellbeing_missing = "Warwick-Edinburgh Mental Wellbeing Scale missing",
                      swemwbs_total = "Short Warwick-Edinburgh Mental Wellbeing Scale (higher = greater wellbeing)",
                      swemwbs_cat = "Short Warwick-Edinburgh Mental Wellbeing Scale category",
                      loneliness = "UCLA Loneliness Scale (higher = more lonely)",
                      loneliness_nas = "UCLA Loneliness Scale NAs",
                      loneliness_missing = "UCLA Loneliness Scale missing",
                      emo_inf = "General Help Seeking Qstnnaire Informal Sources (higher = more help seeking)",
                      emo_form = "General Help Seeking Qstnnaire Formal Sources (higher = more help seeking)",
                      emo_sch = "General Help Seeking Qstnnaire School (higher = more help seeking from school)",
                      emo_total = "General Help Seeking Questionnaire (higher = more help seeking)",
                      emo_nas = "General Help Seeking Questionnaire NAs",
                      emo_missing = "General Help Seeking Questionnaire missing",
                      brs_total = "Brief Resilience Scale (higher = more resilient)",
                      brs_nas = "Brief Resilience Scale NAs",
                      brs_mean = "Brief Resilience Scale mean",
                      brs_cat = "Brief Resilience Scale category",
                      brs_missing = "Brief Resilience Scale missing",
                      soc_sup_fam = "MSPSS family (higher = less social support from family)",
                      soc_sup_frnd = "MSPSS friend (higher = less social support from friends)",
                      soc_sup_total = "MSPSS total (higher = less overall social support)",
                      soc_sup_nas = "MSPSS NAs",
                      soc_sup_missing = "MSPSS missing",
                      awb2_1_illhealth_1 = "How often do you feel sad or empty?",
                      awb2_1_illhealth_2 = "How often do you worry when you think you have done poorly at something?",
                      awb2_1_illhealth_3 = "How often do you feel afraid to be home alone?",
                      awb2_1_illhealth_4 = "How often do you feel nothing is much fun anymore?",
                      awb2_1_illhealth_5 = "How often do you worry that something awful will happen to someone in family?",
                      awb2_1_illhealth_6 = "How often do you feel afraid of being in crowded places?",
                      awb2_1_illhealth_7 = "How often do you worry what others think of you?",
                      awb2_1_illhealth_8 = "How often do you have trouble sleeping?",
                      awb2_1_illhealth_9 = "How often do you feel scared to sleep alone?",
                      awb2_1_illhealth_10 = "How often do you have problems with appetite?",
                      awb2_1_illhealth_11 = "How often do you suddenly become dizzy/faint for no reason?",
                      awb2_1_illhealth_12 = "How often do you have to do some things over and over again?",
                      awb2_1_illhealth_13 = "How often do you have no energy for things?",
                      awb2_1_illhealth_14 = "How often do you suddenly tremble/shake for no reason?",
                      awb2_1_illhealth_15 = "How often is it when you can't think clearly?",
                      awb2_1_illhealth_16 = "How often do you feel worthless?",
                      awb2_1_illhealth_17 = "How often do you think special thoughts to stop bad happening?",
                      awb2_1_illhealth_18 = "How often do you think about death?",
                      awb2_1_illhealth_19 = "How often do you feel like you don't want to move?",
                      awb2_1_illhealth_20 = "How often do you worry about being scared for no reason?",
                      awb2_1_illhealth_21 = "How often do you feel you are tired alot?",
                      awb2_1_illhealth_22 = "How often do you feel afraid you will make a fool of yourself?",
                      awb2_1_illhealth_23 = "How often do you do something the right way to stop bad things happening?",
                      awb2_1_illhealth_24 = "How often do you feel restless?",
                      awb2_1_illhealth_25 = "How often do you worry something bad will happen to you?",
                      awb2_2_optmstc_1_a4 = "Have you felt optimistic about the future over past 2 weeks?",
                      awb2_2_useful_2_a4 = "Have you felt useful over past 2 weeks?",
                      awb2_2_relxed_3_a4 = "Have you felt relaxed over the past 2 weeks?",
                      awb2_2_problems_4_a4 = "Have you dealt with problems well over the past 2 weeks?",
                      awb2_2_think_clr_5_a4 = "Have you been thinking clearly over the past 2 weeks?",
                      awb2_2_close_othrs_6_a4 = "Have you felt close to others over the past 2 weeks?",
                      awb2_2_own_mnd_7_a4 = "Have you made your own mind up about things over past 2 weeks?",
                      awb2_9_trust = "Would you say most people can be trusted/you can't be too careful?",
                      awb2_9_seek_hlp_ppl_2 = "How likely would you seek help from a friend?",
                      awb2_9_seek_hlp_ppl_3 = "How likely would you seek help from a parent/carer?",
                      awb2_9_seek_hlp_ppl_4 = "How likely would you seek help from another relative/family member?",
                      awb2_9_seek_hlp_ppl_5 = "How likely would you seek help from a mental health professional?",
                      awb2_9_seek_hlp_ppl_6 = "How likely would you seek help from a phone helpline?",
                      awb2_9_seek_hlp_ppl_7 = "How likely would you seek help from a doctor/GP?",
                      awb2_9_seek_hlp_ppl_8 = "How likely would you seek help from a religious leader?",
                      awb2_9_seek_hlp_ppl_9_a_4 = "How likely would you seek help from a teacher/other school staff?",
                      awb2_9_seek_hlp_ppl_10 = "How likely is it you would not seek help from anyone?",
                      awb2_11_upsetting_3_a4 = "How upsetting if you heard voices others couldn't hear?",
                      awb2_11_upsetting_5_a4 = "How upsetting if you have seen something other couldn't see?",
                      awb2_11_pst_yr_5_a4 = "How often have you seen something others couldn't see in past year?",
                      awb2_11_upsetting_2_a4 = "How upsetting if you thought you were being followed/spied on?",
                      awb2_11_psychosis_1_r4 = "Have you believed you were being sent special messages through TV?",
                      awb2_11_upsetting_1_a4 = "How upsetting if you believed you were being sent special messages?",
                      awb2_11_psychosis_4_r4 = "Have you ever felt under control of a special power?",
                      awb2_11_upsetting_4_a4 = "How upsetting if you felt under control of a special power?",
                      awb2_11_pst_yr_9_a4 = "How often thought you were very special/have special powers?",
                      awb2_5_social_spprt_1 = "Do you feel your family tries to help you?",
                      awb2_5_social_spprt_2 = "Do you get emotional support you need from family?",
                      awb2_5_social_spprt_3 = "Do you feel your friends try to help you?",
                      awb2_5_social_spprt_4 = "Can you count on your friends when things go wrong?",
                      awb2_5_social_spprt_5 = "Can you talk about your problems with your family?",
                      awb2_5_social_spprt_6 = "Do you have friends you can share your joys/sorrows?",
                      awb2_5_social_spprt_7 = "Do you feel your family is willing to help you make decisions?",
                      awb2_5_social_spprt_8 = "Can you talk about your problems with your friends?",
                      awb2_13_fbq_a3 = "What mental health question would you ask every teenager in Bradford?",
                      awb2_3_self_effccy = "Do you feel when you find something hard you can work out what to do?",
                      feedback_mental_hlth = "What mental health question would you ask every teenager in Bradford?",
                      awb2_4_loneliness_1 = "How often do you feel that you lack friendship?",
                      awb2_4_loneliness_2 = "How often do you feel left out?",
                      awb2_4_loneliness_3 = "How often do you feel isolated from others?",
                      awb2_4_loneliness_4 = "How often do you feel alone?",
                      awb7_2_pollution = "What do you think about the air quality in Bradford?",
                      awb7_3_clmte_chnge_feelng = "How pos/neg do you feel about the future of the environment?",
                      awb7_3_what_changes___1 = "Have you made changes to diet to tackle climate change?",
                      awb7_3_what_changes___2 = "Have you made changes to recycling to tackle climate change?",
                      awb7_3_what_changes___3 = "Have you made changes to travel to tackle climate change?",
                      awb7_3_what_changes___4 = "Have you made changes to spending to tackle climate change?",
                      awb7_3_what_changes___5 = "Have you been more involved with climate activism?",
                      awb7_3_what_changes___6 = "Have you made other changes to tackle climate change?",
                      awb7_3_no_changes_reason___1 = "You think large polluters should change before individuals",
                      awb7_3_no_changes_reason___2 = "You do not think eco-friendly alternatives are as good",
                      awb7_3_no_changes_reason___3 = "It is too expensive to make changes",
                      awb7_3_no_changes_reason___4 = "You dont have the time to make changes",
                      awb7_3_no_changes_reason___5 = "You dont know how to make changes",
                      awb7_3_no_changes_reason___6 = "You dont feel it is your responsibility to make changes",
                      awb7_3_no_changes_reason___7 = "You dont think your changes will effect climate change",
                      awb7_3_no_changes_reason___8 = "You dont need to change because climate change effects are exaggerated",
                      awb7_3_no_changes_reason___9 = "You are not interested in making changes",
                      awb7_3_no_changes_reason___10 = "You have othe reasons you havent made changes")
                      
                      
                      
                      # export

saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module2_labelled.rds")



  