# Module 2 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module2_derived.rds")

module <- module %>%
  set_variable_labels(aow_recruitment_id = "Age of Wonder recruitment ID",
                      year_group = "School year group",
                      age_survey_m = "Age (months) at survey date",
                      age_survey_y = "Age (years) at survey date",
                      survey_date = "Date survey taken",
                      survey_version = "Survey version",
                      survey_mode = "Survey taken online or offline?",
                      awb2_1_illhealth_1 = "I feel sad or empty",
                      awb2_1_illhealth_2 = "I worry when I think I have done poorly at something",
                      awb2_1_illhealth_3 = "I would feel afraid of being on my own at home",
                      awb2_1_illhealth_4 = "Nothing is much fun anymore",
                      awb2_1_illhealth_5 = "I worry that something awful will happen to family",
                      awb2_1_illhealth_6 = "I am afraid of being in crowded places",
                      awb2_1_illhealth_7 = "I wory what other people think of me",
                      awb2_1_illhealth_8 = "I have trouble sleeping",
                      awb2_1_illhealth_9 = "I feel scared if I have to sleep on my own",
                      awb2_1_illhealth_10 = "I have problems with my appetite",
                      awb2_1_illhealth_11 = "I become dizzy/faint with no reason",
                      awb2_1_illhealth_12 = "I have to do some things over and over again",
                      awb2_1_illhealth_13 = "I have no energy for things",
                      awb2_1_illhealth_14 = "I start to tremble/shake with no reason",
                      awb2_1_illhealth_15 = "I cannot think clearly",
                      awb2_1_illhealth_16 = "I feel worthless",
                      awb2_1_illhealth_17 = "I have to think special thoughts to stop bad things happening",
                      awb2_1_illhealth_18 = "I think about death",
                      awb2_1_illhealth_19 = "I feel like I don't want to move",
                      awb2_1_illhealth_20 = "I worry about getting scared with nothing to be afraid of",
                      awb2_1_illhealth_21 = "I am tired a lot",
                      awb2_1_illhealth_22 = "I'm afraid I will make a fool of myself in front of people",
                      awb2_1_illhealth_23 = "I have to do somethings in the right way to stop bad things happening",
                      awb2_1_illhealth_24 = "I feel restless",
                      awb2_1_illhealth_25 = "I worry something bad will happen to me",
                      awb2_4_loneliness_1 = "How often do you feel you lack friendship?",
                      awb2_4_loneliness_2 = "How often do you feel left out?",
                      awb2_4_loneliness_3 = "How often do you feel isolated from others?",
                      awb2_4_loneliness_4 = "How often do you feel alone?",
                      awb2_9_seek_hlp_ppl_1_r4 = "How likely would you seek help from partner?",
                      awb2_9_seek_hlp_ppl_11 = "Would you seek help from someone not listed? List in space provided",
                      awb2_11_psychosis_3_r4 = "Have you ever heard voices that others cannot hear?",
                      awb2_11_psychosis_5_r4 = "Have you ever seen something others cannot see?",
                      awb2_11_psychosis_2_r4 = "Have you ever thought you was being followed/spied on?",
                      awb2_11_psychosis_10_r4 = "Have other people ever read your thoughts?",
                      awb2_11_pwrs_read_a4 = "Do you think people use special powers to read your thoughts?",
                      awb2_11_psychosis_1_r4 = "Have you thought you were being sent messages through TV arranged just for you?",
                      awb2_11_psychosis_4_r4 = "Have you ever felt under control of a special power?",
                      awb2_11_psychosis_9_r4 = "Have you ever felt like you have special powers?",
                      awb7_3_worry_specify = "Are you not worried about impact of climate change? Please specify",
                      awb7_3_chngs_plse_specify = "What changes have you made to tackle climate change? Specify",
                      awb7_3_no_chnges_specify = "What reason have you not made changes to tackle climate change? Specify",
                      feedback_mental_hlth = "Feedback for mental health questions",
                      rcad_ga = "Revised childrens anxiety and depression scale. General anxiety",
                      rcad_md = "Revised childrens anxiety and depression scale. Major depression",
                      rcad_total = "Revised childrens anxiety and depression scale. Total",
                      rcad_nas = "Revised childrens anxiety and depression scale. NAs",
                      rcad_ga_miss = "Revised childrens anxiety and depression scale. General anxiety NAs",
                      rcad_md_miss = "Revised childrens anxiety and depression scale. Major depression NAs",
                      rcad_missing = "Revised childrens anxiety and depression scale. Total NAs",
                      depression_int = "Depression int",
                      depression_factor = "Depression factor",
                      anxiety_int = "Anxiety int",
                      anxiety_factor = "Anxiety factor",
                      total_int = "Total int",
                      total_factor = "Total factor",
                      rcad_md_t = "Revised childrens anxiety and depression scale. Major depression total",
                      rcad_ga_t = "Revised childrens anxiety and depression scale. General anxiety total",
                      rcad_total_t = "Revised childrens anxiety and depression scale. Total sum",
                      rcad_md_cat = "Revised childrens anxiety and depression scale. Major depression category",
                      rcad_ga_cat = "Revised childrens anxiety and depression scale. General anxiety category",
                      rcad_total_cat = "Revised childrens anxiety and depression scale. Total category",
                      wellbeing = "Warwick-Edinburgh Mental Wellbeing Scale",
                      wellbeing_nas = "Warwick-Edinburgh Mental Wellbeing Scale NAs",
                      wellbeing_missing = "Warwick-Edinburgh Mental Wellbeing Scale missing",
                      swemwbs_total = "Short Warwick-Edinburgh Mental Wellbeing Scale total",
                      swemwbs_cat = "Short Warwick-Edinburgh Mental Wellbeing Scale category",
                      loneliness = "UCLA Loneliness Scale",
                      loneliness_nas = "UCLA Loneliness Scale NAs",
                      loneliness_missing = "UCLA Loneliness Scale missing",
                      emo_inf = "General Help Seeking Questionnaire",
                      emo_form = "General Help Seeking Questionnaire",
                      emo_total = "General Help Seeking Questionnaire total",
                      emo_nas = "General Help Seeking Questionnaire NAs",
                      emo_missing = "General Help Seeking Questionnaire missing",
                      brs_total = "Brief Resilience Scale total",
                      brs_nas = "Brief Resilience Scale NAs",
                      brs_mean = "Brief Resilience Scale mean",
                      brs_cat = "Brief Resilience Scale category",
                      brs_missing = "Brief Resilience Scale missing",
                      soc_sup_fam = "MSPSS family",
                      soc_sup_frnd = "MSPSS friend",
                      soc_sup_total = "MSPSS total",
                      soc_sup_nas = "MSPSS NAs",
                      soc_sup_missing = "MSPSS missing")





# export
saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module2_labelled.rds")



  