# Module 2 survey labelling and tidying

source("tools/aow_survey_functions.R")

module <- readRDS("U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module2_derived.rds")



module <- module %>%
  mutate(awb2_1_illhealth_1 = awb2_1_illhealth_1 + 1,
         awb2_1_illhealth_2 = awb2_1_illhealth_2 + 1,
         awb2_1_illhealth_3 = awb2_1_illhealth_3 + 1,
         awb2_1_illhealth_4 = awb2_1_illhealth_4 + 1,
         awb2_1_illhealth_5 = awb2_1_illhealth_5 + 1,
         awb2_1_illhealth_6 = awb2_1_illhealth_6 + 1,
         awb2_1_illhealth_7 = awb2_1_illhealth_7 + 1,
         awb2_1_illhealth_8 = awb2_1_illhealth_8 + 1,
         awb2_1_illhealth_9 = awb2_1_illhealth_9 + 1,
         awb2_1_illhealth_10 = awb2_1_illhealth_10 + 1,
         awb2_1_illhealth_11 = awb2_1_illhealth_11 + 1,
         awb2_1_illhealth_12 = awb2_1_illhealth_12 + 1,
         awb2_1_illhealth_13 = awb2_1_illhealth_13 + 1,
         awb2_1_illhealth_14 = awb2_1_illhealth_14 + 1,
         awb2_1_illhealth_15 = awb2_1_illhealth_15 + 1,
         awb2_1_illhealth_16 = awb2_1_illhealth_16 + 1,
         awb2_1_illhealth_17 = awb2_1_illhealth_17 + 1,
         awb2_1_illhealth_18 = awb2_1_illhealth_18 + 1,
         awb2_1_illhealth_19 = awb2_1_illhealth_19 + 1,
         awb2_1_illhealth_20 = awb2_1_illhealth_20 + 1,
         awb2_1_illhealth_21 = awb2_1_illhealth_21 + 1,
         awb2_1_illhealth_22 = awb2_1_illhealth_22 + 1,
         awb2_1_illhealth_23 = awb2_1_illhealth_23 + 1,
         awb2_1_illhealth_24 = awb2_1_illhealth_24 + 1,
         awb2_1_illhealth_25 = awb2_1_illhealth_25 + 1,
         awb2_2_life_stsfctn_1 = awb2_2_life_stsfctn_1 + 1,
         awb2_2_life_stsfctn_2 = awb2_2_life_stsfctn_2 + 1,
         awb2_2_life_stsfctn_3 = awb2_2_life_stsfctn_3 + 1,
         awb2_2_life_stsfctn_4 = awb2_2_life_stsfctn_4 + 1,
         awb2_2_life_stsfctn_5 = awb2_2_life_stsfctn_5 + 1,
         awb2_2_life_stsfctn_6 = awb2_2_life_stsfctn_6 + 1,
         awb2_4_loneliness_1 = awb2_4_loneliness_1 + 1,
         awb2_4_loneliness_2 = awb2_4_loneliness_2 + 1,
         awb2_4_loneliness_3 = awb2_4_loneliness_3 + 1,
         awb2_4_loneliness_4 = awb2_4_loneliness_4 + 1,
         awb2_9_seek_hlp_ppl_1_r4 = awb2_9_seek_hlp_ppl_1_r4 + 1,
         awb2_11_psychosis_3_r4 = awb2_11_psychosis_3_r4 + 1,
         awb2_11_psychosis_5_r4 = awb2_11_psychosis_5_r4 + 1,
         awb2_11_psychosis_10_r4 = awb2_11_psychosis_10_r4 + 1,
         awb2_11_psychosis_1_r4 = awb2_11_psychosis_1_r4 + 1,
         awb2_11_psychosis_4_r4 = awb2_11_psychosis_4_r4 + 1,
         awb2_11_psychosis_9_r4 = awb2_11_psychosis_9_r4 + 1,
         awb2_5_social_spprt_1 = awb2_5_social_spprt_1 + 1,
         awb2_5_social_spprt_2 = awb2_5_social_spprt_2 + 1,
         awb2_5_social_spprt_3 = awb2_5_social_spprt_3 + 1,
         awb2_5_social_spprt_4 = awb2_5_social_spprt_4 + 1,
         awb2_5_social_spprt_5 = awb2_5_social_spprt_5 + 1,
         awb2_5_social_spprt_6 = awb2_5_social_spprt_6 + 1,
         awb2_5_social_spprt_7 = awb2_5_social_spprt_7 + 1,
         awb2_5_social_spprt_8 = awb2_5_social_spprt_8 + 1) %>%
  set_value_labels(awb2_1_illhealth_1 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_2 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_3 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_4 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_5 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_6 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_7 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_8 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_9 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_10 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_11 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_12 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_13 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_14 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_15 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_16 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_17 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_18 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_19 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_20 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_21 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_22 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_23 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_24 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_1_illhealth_25 = c("Never" = 1, "Sometimes" = 2, "Often" = 3, "Always" = 4),
                   awb2_2_life_stsfctn_1 = c("1 (completely happy)" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7 (not at all happy)" = 7),
                   awb2_2_life_stsfctn_2 = c("1 (completely happy)" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7 (not at all happy)" = 7),
                   awb2_2_life_stsfctn_3 = c("1 (completely happy)" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7 (not at all happy)" = 7),
                   awb2_2_life_stsfctn_4 = c("1 (completely happy)" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7 (not at all happy)" = 7),
                   awb2_2_life_stsfctn_5 = c("1 (completely happy)" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7 (not at all happy)" = 7),
                   awb2_2_life_stsfctn_6 = c("1 (completely happy)" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7 (not at all happy)" = 7),
                   awb2_4_loneliness_1 = c("Hardly ever" = 1, "Some of the time" = 2, "Often" = 3),
                   awb2_4_loneliness_2 = c("Hardly ever" = 1, "Some of the time" = 2, "Often" = 3),
                   awb2_4_loneliness_3 = c("Hardly ever" = 1, "Some of the time" = 2, "Often" = 3),
                   awb2_4_loneliness_4 = c("Hardly ever" = 1, "Some of the time" = 2, "Often" = 3),
                   awb2_11_psychosis_2_r4 = c("Yes, definitely" = 1, "Yes, maybe" = 2, "No, never" = 3),
                   awb2_11_pwrs_read_a4 = c("Yes, definitely" = 1, "Yes, maybe" = 2, "No, never" = 3),
                   awb2_11_psychosis_1_r4 = c("Yes, definitely" = 1, "Yes, maybe" = 2, "No, never" = 3),
                   awb2_11_psychosis_4_r4 = c("Yes, definitely" = 1, "Yes, maybe" = 2, "No, never" = 3),
                   awb2_11_psychosis_9_r4 = c("Yes, definitely" = 1, "Yes, maybe" = 2, "No, never" = 3),
                   awb2_9_seek_hlp_ppl_1_r4 = c("1 (extremely unlikely)" = 1,
                                               "2" = 2,
                                               "3 (unlikely)" = 3,
                                               "4" = 4,
                                               "5 (likely)" = 5,
                                               "6" = 6,
                                               "7 (extremely likely)" = 7,
                                               "I don't have a girlfriend/boyfriend/partner" = 8),
                   awb2_11_psychosis_3_r4 = c("Yes, definitely" = 1,
                                              "Yes, maybe" = 2,
                                              "No, never" = 3),
                   awb2_11_psychosis_5_r4 = c("Yes, definitely" = 1,
                                              "Yes, maybe" = 2,
                                              "No, never" = 3),
                   awb2_11_psychosis_10_r4 = c("Yes, definitely" = 1,
                                               "Yes, maybe" = 2,
                                               "No, never" = 3),
                   awb2_11_psychosis_1_r4 = c("Yes, definitely" = 1,
                                               "Yes, maybe" = 2,
                                               "No, never" = 3),
                   awb2_11_psychosis_4_r4 = c("Yes, definitely" = 1,
                                               "Yes, maybe" = 2,
                                               "No, never" = 3),
                   awb2_11_psychosis_9_r4 = c("Yes, definitely" = 1,
                                               "Yes, maybe" = 2,
                                               "No, never" = 3),
                   awb2_5_social_spprt_1 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_2 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_3 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_4 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_5 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_6 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_7 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3),
                   awb2_5_social_spprt_8 = c("Not true" = 1,
                                             "Somewhat true" = 2,
                                             "Very true" = 3))


module <- module %>%
  set_variable_labels(aow_recruitment_id = "Age of Wonder recruitment ID",
                      year_group = "School year group",
                      age_survey_m = "Age (months) at survey date",
                      age_survey_y = "Age (years) at survey date",
                      survey_date = "Date survey taken",
                      survey_version = "Survey version",
                      survey_mode = "Survey taken online or offline?",
                      awb2_9_seek_hlp_ppl_1_r4 = "How likely would you seek help from partner?",
                      awb2_9_seek_hlp_ppl_11 = "Would you seek help from someone not listed? List in space provided",
                      awb2_11_psychosis_3_r4 = "Have you ever heard voices that others cannot hear?",
                      awb2_11_psychosis_5_r4 = "Have you ever seen something others cannot see?",
                      awb2_11_psychosis_2_r4 = "Have you ever thought you was being followed/spied on?",
                      awb2_11_psychosis_10_r4 = "Have other people ever read your thoughts?",
                      awb2_11_pwrs_read_a4 = "Do you think people use special powers to read your thoughts?",
                      awb2_11_psychosis_1_r4 = "Have you thought you were being sent messages through TV arranged just for you?",
                      awb2_11_psychosis_4_r4 = "Have you ever felt under control of a special power?",
                      awb2_11_psychosis_9_r4 = "Have you ever felt like you have special powers?",
                      awb7_3_worry_specify = "Are you not worried about impact of climate change? Please specify",
                      awb7_3_chngs_plse_specify = "What changes have you made to tackle climate change? Specify",
                      awb7_3_no_chnges_specify = "What reason have you not made changes to tackle climate change? Specify",
                      feedback_mental_hlth = "Feedback for mental health questions",
                      rcad_ga = "Revised childrens anxiety and depression scale. General anxiety",
                      rcad_md = "Revised childrens anxiety and depression scale. Major depression",
                      rcad_total = "Revised childrens anxiety and depression scale. Total",
                      rcad_nas = "Revised childrens anxiety and depression scale. NAs",
                      rcad_ga_miss = "Revised childrens anxiety and depression scale. General anxiety NAs",
                      rcad_md_miss = "Revised childrens anxiety and depression scale. Major depression NAs",
                      rcad_missing = "Revised childrens anxiety and depression scale. Total NAs",
                      depression_int = "Depression int",
                      depression_factor = "Depression factor",
                      anxiety_int = "Anxiety int",
                      anxiety_factor = "Anxiety factor",
                      total_int = "Total int",
                      total_factor = "Total factor",
                      rcad_md_t = "Revised childrens anxiety and depression scale. Major depression total",
                      rcad_ga_t = "Revised childrens anxiety and depression scale. General anxiety total",
                      rcad_total_t = "Revised childrens anxiety and depression scale. Total sum",
                      rcad_md_cat = "Revised childrens anxiety and depression scale. Major depression category",
                      rcad_ga_cat = "Revised childrens anxiety and depression scale. General anxiety category",
                      rcad_total_cat = "Revised childrens anxiety and depression scale. Total category",
                      wellbeing = "Warwick-Edinburgh Mental Wellbeing Scale",
                      wellbeing_nas = "Warwick-Edinburgh Mental Wellbeing Scale NAs",
                      wellbeing_missing = "Warwick-Edinburgh Mental Wellbeing Scale missing",
                      swemwbs_total = "Short Warwick-Edinburgh Mental Wellbeing Scale total",
                      swemwbs_cat = "Short Warwick-Edinburgh Mental Wellbeing Scale category",
                      loneliness = "UCLA Loneliness Scale",
                      loneliness_nas = "UCLA Loneliness Scale NAs",
                      loneliness_missing = "UCLA Loneliness Scale missing",
                      emo_inf = "General Help Seeking Questionnaire",
                      emo_form = "General Help Seeking Questionnaire",
                      emo_total = "General Help Seeking Questionnaire total",
                      emo_nas = "General Help Seeking Questionnaire NAs",
                      emo_missing = "General Help Seeking Questionnaire missing",
                      brs_total = "Brief Resilience Scale total",
                      brs_nas = "Brief Resilience Scale NAs",
                      brs_mean = "Brief Resilience Scale mean",
                      brs_cat = "Brief Resilience Scale category",
                      brs_missing = "Brief Resilience Scale missing",
                      soc_sup_fam = "MSPSS family",
                      soc_sup_frnd = "MSPSS friend",
                      soc_sup_total = "MSPSS total",
                      soc_sup_nas = "MSPSS NAs",
                      soc_sup_missing = "MSPSS missing",
                      awb2_1_illhealth_1 = "How often do you feel sad or empty?",
                      awb2_1_illhealth_2 = "How often do you worry when you think you have done poorly at something?",
                      awb2_1_illhealth_3 = "How often do you feel afraid to be home alone?",
                      awb2_1_illhealth_4 = "How often do you feel nothing is much fun anymore?",
                      awb2_1_illhealth_5 = "How often do you worry that something awful will happen to someone in family?",
                      awb2_1_illhealth_6 = "How often do you feel afraid of being in crowded places?",
                      awb2_1_illhealth_7 = "How often do you worry what others think of you?",
                      awb2_1_illhealth_8 = "How often do you have trouble sleeping?",
                      awb2_1_illhealth_9 = "How often do you feel scared to sleep alone?",
                      awb2_1_illhealth_10 = "How often do you have problems with appetite?",
                      awb2_1_illhealth_11 = "How often do you suddenly become dizzy/faint for no reason?",
                      awb2_1_illhealth_12 = "How often do you have to do some things over and over again?",
                      awb2_1_illhealth_13 = "How often do you have no energy for things?",
                      awb2_1_illhealth_14 = "How often do you suddenly tremble/shake for no reason?",
                      awb2_1_illhealth_15 = "How often is it when you can't think clearly?",
                      awb2_1_illhealth_16 = "How often do you feel worthless?",
                      awb2_1_illhealth_17 = "How often do you think special thoughts to stop bad happening?",
                      awb2_1_illhealth_18 = "How often do you think about death?",
                      awb2_1_illhealth_19 = "How often do you feel like you don't want to move?",
                      awb2_1_illhealth_20 = "How often do you worry about being scared for no reason?",
                      awb2_1_illhealth_21 = "How often do you feel you are tired alot?",
                      awb2_1_illhealth_22 = "How often do you feel afraid you will make a fool of yourself?",
                      awb2_1_illhealth_23 = "How often do you do something the right way to stop bad things happening?",
                      awb2_1_illhealth_24 = "How often do you feel restless?",
                      awb2_1_illhealth_25 = "How often do you worry something bad will happen to you?",
                      awb2_2_life_stsfctn_1 = "How do you feel about your school work?",
                      awb2_2_life_stsfctn_2 = "How do you feel about the way you look?",
                      awb2_2_life_stsfctn_3 = "How do you feel about your family?",
                      awb2_2_life_stsfctn_4 = "How do you feel about your friends?",
                      awb2_2_life_stsfctn_5 = "How do you feel about the school you go to?",
                      awb2_2_life_stsfctn_6 = "How do you feel about your life as a whole?",
                      awb2_2_optmstc_1_a4 = "Have you felt optimistic about the future over past 2 weeks?",
                      awb2_2_useful_2_a4 = "Have you felt useful over past 2 weeks?",
                      awb2_2_relxed_3_a4 = "Have you felt relaxed over the past 2 weeks?",
                      awb2_2_problems_4_a4 = "Have you dealt with problems well over the past 2 weeks?",
                      awb2_2_think_clr_5_a4 = "Have you been thinking clearly over the past 2 weeks?",
                      awb2_2_close_othrs_6_a4 = "Have you felt close to others over the past 2 weeks?",
                      awb2_2_own_mnd_7_a4 = "Have you made your own mind up about things over past 2 weeks?",
                      awb2_6_family_rltnshp_2 = "How often do you get along with siblings/young people you live with?",
                      awb2_6_family_rltnshp_4 = "Have you stayed away overnight without parents knowing where in past year?",
                      awb2_7_friends_physcl = "How many in-person friends do you have?",
                      awb2_7_friends_onln = "How many online friends do you have?",
                      awb2_7_friends_clse = "Do you have any close friends?",
                      awb2_9_trust = "Would you say most people can be trusted/you can't be too careful?",
                      awb2_9_seek_hlp_trst = "There is someone I trust I would turn to for advise",
                      awb2_9_seek_hlp_ppl_1 = "How likely would you seek help from a girlfriend/boyfriend/partner?",
                      awb2_9_seek_hlp_ppl_2 = "How likely would you seek help from a friend?",
                      awb2_9_seek_hlp_ppl_3 = "How likely would you seek help from a parent/carer?",
                      awb2_9_seek_hlp_ppl_4 = "How likely would you seek help from another relative/family member?",
                      awb2_9_seek_hlp_ppl_5 = "How likely would you seek help from a mental health professional?",
                      awb2_9_seek_hlp_ppl_6 = "How likely would you seek help from a phone helpline?",
                      awb2_9_seek_hlp_ppl_7 = "How likely would you seek help from a doctor/GP?",
                      awb2_9_seek_hlp_ppl_8 = "How likely would you seek help from a religious leader?",
                      awb2_9_seek_hlp_ppl_9 = "How likely would you seek help from a teacher/other school staff?",
                      awb2_9_seek_hlp_ppl_10 = "How likely is it you would not seek help from anyone?",
                      awb2_11_upsetting_3_a4 = "How upsetting if you heard voices others couldn't hear?",
                      awb2_11_upsetting_5_a4 = "How upsetting if you have seen something other couldn't see?",
                      awb2_11_pst_yr_5_a4 = "How often have you seen something others couldn't see in past year?",
                      awb2_11_upsetting_2_a4 = "How upsetting if you thought you were being followed/spied on?",
                      awb2_11_psychosis_10 = "Have you ever thought others could read your thoughts?",
                      awb2_11_psychosis_1 = "Have you believed you were being sent special messages through TV?",
                      awb2_11_psychosis_1_r4 = "Have you believed you were being sent special messages through TV?",
                      awb2_11_upsetting_1_a4 = "How upsetting if you believed you were being sent special messages?",
                      awb2_11_psychosis_4_r4 = "Have you ever felt under control of a special power?",
                      awb2_11_upsetting_4_a4 = "How upsetting if you felt under control of a special power?",
                      awb2_11_psychosis_9 = "Have you ever felt very special/have special powers?",
                      awb2_11_pst_yr_9_a4 = "How often thought you were very special/have special powers?",
                      awb2_11_psychosis_6 = "Have you felt your thoughts were being taken out of your head?",
                      awb2_11_psychosis_7 = "Have you felt someones thoughts were being inserted into your head?",
                      awb2_11_psychosis_8 = "Have you felt your thoughts were so loud that others could hear?",
                      awb2_12_eat_hbt_1_a4 = "Have you limited food consumption to influence weight?",
                      awb2_12_eat_hbt_2_a4 = "Have you not eaten for long periods to influence weight?",
                      awb2_12_eat_hbt_3_a4 = "Has thinking about food/calories made it difficult to concentrate?",
                      awb2_12_eat_hbt_4_a4 = "Has thinking about your weight made it difficult to concentrate?",
                      awb2_12_eat_hbt_7_a4 = "Have you tried to control weight by takin laxatives/vomiting?",
                      awb2_12_eat_hbt_8_a4 = "Have you exercised compulsively to control weight?",
                      awb2_12_eat_hbt_9_a4 = "Have you sensed you lost control over your eating?",
                      awb2_12_eat_hbt_10_a4 = "How many days did you eat an unusual amount of food?",
                      awb2_12_wght_1_a4 = "Has your weight influenced how you judge yourself in past 7 days?",
                      awb2_12_wght_2_a4 = "How dissatisfied have you been with your weight?",
                      awb2_5_social_spprt_1 = "Do you feel your family tries to help you?",
                      awb2_5_social_spprt_2 = "Do you get emotional support you need from family?",
                      awb2_5_social_spprt_3 = "Do you feel your friends try to help you?",
                      awb2_5_social_spprt_4 = "Can you count on your friends when things go wrong?",
                      awb2_5_social_spprt_5 = "Can you talk about your problems with your family?",
                      awb2_5_social_spprt_6 = "Do you have friends you can share your joys/sorrows?",
                      awb2_5_social_spprt_7 = "Do you feel your family is willing to help you make decisions?",
                      awb2_5_social_spprt_8 = "Can you talk about your problems with your friends?",
                      awb2_13_fbq_a3 = "What mental health question would you ask every teenager in Bradford?",
                      awb2_3_self_effccy = "Do you feel when you find something hard you can work out what to do?",
                      feedback_mental_hlth = "What mental health question would you ask every teenager in Bradford?",
                      awb2_4_loneliness_1 = "How often do you feel that you lack friendship?",
                      awb2_4_loneliness_2 = "How often do you feel left out?",
                      awb2_4_loneliness_3 = "How often do you feel isolated from others?",
                      awb2_4_loneliness_4 = "How often do you feel alone?",
                      girlfriend_boyfriend_or_pa = "Would you seek help from partner RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_1_a3 = "Would you seek help from partner RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_1_r4 = "Would you seek help from partner RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_2_a3 = "Would you seek help from friend RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_3_a3 = "Would you seek help from parent RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_4_a3 = "Would you seek help from family RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_5_a3 = "Would you seek help from mental health professional RE suicide?",
                      awb2_9_seek_hlp_sui_6_a3 = "Would you seek help from phone helpline RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_7_a3 = "Would you seek help from GP RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_8_a3 = "Would you seek help from religious leader RE suicide?",
                      awb2_9_seek_hlp_sui_10_a3 = "Would you seek help from school staff RE suicidal?",
                      awb2_9_seek_hlp_sui_9_a3 = "You would not seek help from anyone RE suicidal thoughts?",
                      awb2_9_seek_hlp_sui_othr_a3 = "Would you seek help from another not listed RE suicide?",
                      awb2_9_seek_hlp_sui_11_a3 = "Please list others youd seek help from RE suicidal thoughts?",
                      friend_not_related_to_you = "Would you seek help from a friend RE suicidal thoughts?",
                      parent = "Would you seek help from parent RE suicidal thoughts?",
                      other_relative_family_memb = "Would you seek help from family RE suicidal thoughts?",
                      mental_health_professional = "Would you seek help from mental health professional RE suicide?",
                      phone_helpline_e_g_lifelin = "Would you seek help from phone line RE suicidal thoughts?",
                      doctor_gp = "Would you seek help from GP RE suicidal thoughts?",
                      religious_leader = "Would you seek help from religious leader RE suicide?",
                      teacher_or_other_school_st = "Would you seek help from school staff RE suicide?",
                      i_would_not_seek_help_from = "You would not seek help from anyone RE suicdal thoughts?",
                      i_would_seek_help_from_ano = "Would you seek help from another not listed RE suicide?",
                      awb7_2_pollution = "What do you think about the air quality in Bradford?",
                      awb7_3_clmte_chnge_feelng = "How pos/neg do you feel about the future of the environment?",
                      awb7_3_what_changes___1 = "Have you made changes to diet to tackle climate change?",
                      awb7_3_what_changes___2 = "Have you made changes to recycling to tackle climate change?",
                      awb7_3_what_changes___3 = "Have you made changes to travel to tackle climate change?",
                      awb7_3_what_changes___4 = "Have you made changes to spending to tackle climate change?",
                      awb7_3_what_changes___5 = "Have you been more involved with climate activism?",
                      awb7_3_what_changes___6 = "Have you made other changes to tackle climate change?",
                      awb7_3_no_changes_reason___1 = "You think large polluters should change before individuals",
                      awb7_3_no_changes_reason___2 = "You do not think eco-friendly alternatives are as good",
                      awb7_3_no_changes_reason___3 = "It is too expensive to make changes",
                      awb7_3_no_changes_reason___4 = "You dont have the time to make changes",
                      awb7_3_no_changes_reason___5 = "You dont know how to make changes",
                      awb7_3_no_changes_reason___6 = "You dont feel it is your responsibility to make changes",
                      awb7_3_no_changes_reason___7 = "You dont think your changes will effect climate change",
                      awb7_3_no_changes_reason___8 = "You dont need to change because climate change effects are exaggerated",
                      awb7_3_no_changes_reason___9 = "You are not interested in making changes",
                      awb7_3_no_changes_reason___10 = "You have othe reasons you havent made changes")
                      
                      
                      
                      # export

saveRDS(module, "U:/Born In Bradford - Confidential/Data/BiB/processing/AoW/survey/data/aow_survey_module2_labelled.rds")



  